"""empty message

Revision ID: 25f6827f640c
Revises: 
Create Date: 2022-03-23 16:07:54.727458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f6827f640c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iletisim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numara', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('adress', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('off_grid_esya')
    op.drop_table('musteri')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musteri',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('isim', sa.VARCHAR(), nullable=True),
    sa.Column('soyisim', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('numara', sa.VARCHAR(), nullable=True),
    sa.Column('proje_tipi', sa.VARCHAR(), nullable=True),
    sa.Column('file', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('off_grid_esya',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('esya', sa.VARCHAR(), nullable=True),
    sa.Column('adet', sa.INTEGER(), nullable=True),
    sa.Column('birstw', sa.INTEGER(), nullable=True),
    sa.Column('GundeKullanimSuresi', sa.INTEGER(), nullable=True),
    sa.Column('GunduzKullanimSuresi', sa.INTEGER(), nullable=True),
    sa.Column('AksamKullanimSuresi', sa.INTEGER(), nullable=True),
    sa.Column('Gepa', sa.INTEGER(), nullable=True),
    sa.Column('OffGridId', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('iletisim')
    # ### end Alembic commands ###
