"""empty message

Revision ID: 29d691a047a2
Revises: 25f6827f640c
Create Date: 2022-03-23 16:11:25.022813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d691a047a2'
down_revision = '25f6827f640c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iletisim', sa.Column('number', sa.String(), nullable=True))
    op.drop_column('iletisim', 'numara')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iletisim', sa.Column('numara', sa.VARCHAR(), nullable=True))
    op.drop_column('iletisim', 'number')
    # ### end Alembic commands ###
