"""empty message

Revision ID: 5d09fdd99f44
Revises: 29d691a047a2
Create Date: 2022-03-23 22:24:41.378281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d09fdd99f44'
down_revision = '29d691a047a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usrtest1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rltest1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('tsts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tsts'], ['usrtest1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rltest1')
    op.drop_table('usrtest1')
    # ### end Alembic commands ###
